# Generated by Django 6.0.4 on 2026-04-22 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('grupo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('fase', models.CharField(choices=[('GR', 'Fase de Grupos'), ('R32', 'Ronda de 32'), ('R16', 'Octavos de Final'), ('QF', 'Cuartos de Final'), ('SF', 'Semifinal'), ('TP', 'Tercer Puesto'), ('FI', 'Final')], max_length=3)),
                ('grupo', models.CharField(blank=True, max_length=1)),
                ('label_local', models.CharField(blank=True, max_length=60)),
                ('label_visitante', models.CharField(blank=True, max_length=60)),
                ('goles_local_real', models.SmallIntegerField(blank=True, null=True)),
                ('goles_visitante_real', models.SmallIntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_local', to='core.pais')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_visitante', to='core.pais')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.SmallIntegerField()),
                ('goles_visitante', models.SmallIntegerField()),
                ('puntos', models.SmallIntegerField(blank=True, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='core.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='core.perfilusuario')),
            ],
            options={
                'unique_together': {('usuario', 'partido')},
            },
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
