# Generated by Django 6.0.4 on 2026-04-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pais_partido_perfilusuario_prediccion_delete_opcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='clasificado_pred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_pred', to='core.pais'),
        ),
    ]
