# Generated by Django 6.0.4 on 2026-04-23 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prediccion_clasificado_pred'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorneoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueado', models.BooleanField(default=False)),
                ('bloqueado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración del torneo',
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='clasificado_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_reales', to='core.pais'),
        ),
    ]
