# Generated by Django 4.2.30 on 2026-04-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_torneoconfig_partido_clasificado_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='torneoconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TerceroManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField()),
                ('grupo', models.CharField(max_length=1)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros_manuales', to='core.perfilusuario')),
            ],
            options={
                'ordering': ['posicion'],
                'unique_together': {('usuario', 'posicion')},
            },
        ),
        migrations.CreateModel(
            name='ClasificacionManualGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=1)),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_cuarto', to='core.pais')),
                ('primero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_primero', to='core.pais')),
                ('segundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_segundo', to='core.pais')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_tercero', to='core.pais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_manuales', to='core.perfilusuario')),
            ],
            options={
                'ordering': ['grupo'],
                'unique_together': {('usuario', 'grupo')},
            },
        ),
    ]
