# Generated by Django 6.0.4 on 2026-04-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_torneoconfig_partido_clasificado_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=1)),
                ('posicion', models.PositiveSmallIntegerField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_grupo', to='core.pais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_grupo', to='core.perfilusuario')),
            ],
            options={
                'ordering': ['grupo', 'posicion'],
                'unique_together': {('usuario', 'grupo', 'posicion')},
            },
        ),
    ]
